// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ebZhztsXFPrH0fqqalOZjLIJzn7XJno',
    appId: '1:846983690123:web:b0c89fc1e0c729dff2a18e',
    messagingSenderId: '846983690123',
    projectId: 'webprofil-a8956',
    authDomain: 'webprofil-a8956.firebaseapp.com',
    storageBucket: 'webprofil-a8956.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb_cuzN3IX0CD4xpLNptgt8rBSDpEWoF8',
    appId: '1:846983690123:android:452825617c1b6ae3f2a18e',
    messagingSenderId: '846983690123',
    projectId: 'webprofil-a8956',
    storageBucket: 'webprofil-a8956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1UoPirZmiA2RO5QJMgRKtgUgGQxdS-ng',
    appId: '1:846983690123:ios:4d9c144259f3fefef2a18e',
    messagingSenderId: '846983690123',
    projectId: 'webprofil-a8956',
    storageBucket: 'webprofil-a8956.firebasestorage.app',
    iosBundleId: 'com.example.webprofil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1UoPirZmiA2RO5QJMgRKtgUgGQxdS-ng',
    appId: '1:846983690123:ios:4d9c144259f3fefef2a18e',
    messagingSenderId: '846983690123',
    projectId: 'webprofil-a8956',
    storageBucket: 'webprofil-a8956.firebasestorage.app',
    iosBundleId: 'com.example.webprofil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4ebZhztsXFPrH0fqqalOZjLIJzn7XJno',
    appId: '1:846983690123:web:c9b13d79c98295a9f2a18e',
    messagingSenderId: '846983690123',
    projectId: 'webprofil-a8956',
    authDomain: 'webprofil-a8956.firebaseapp.com',
    storageBucket: 'webprofil-a8956.firebasestorage.app',
  );

}